version: '3.8'

services:
  postgres:
    build:
      context: docker/postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    container_name: data_base
    networks:
      - back

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - back

networks:
  back:
    name: back