version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Symfony/Dockerfile
    container_name: php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    networks:
      - front
      - back

  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - front

networks:
  back:
    name: back
  front:
    name: front