version: '3.8'

services:
  postgres:
    build:
      context: docker/postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    container_name: data_base

  php:
    build:
      context: .
      dockerfile: docker/Symfony/Dockerfile
    container_name: php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
