version: '3'
services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
